public class ReplicatedEventType {
    public static final String INSTANCE_CREATED = 'instance.created';
    public static final String INSTANCE_UPGRADE_COMPLETED = 'instance.upgrade_completed';
    public static final String INSTANCE_INACTIVE = 'instance.inactive';
    public static final String CUSTOMER_CREATED = 'customer.created';
    public static final String CUSTOMER_LICENSE_EXPIRING = 'customer.license_expiring';
    public static final String CUSTOMER_PENDING_SIGNUP = 'customer.pending_signup';
    public static final String CUSTOMER_UPDATED = 'customer.updated';
    public static final String RELEASE_ASSET_DOWNLOADED = 'release.asset_downloaded';
}
